# Generated by Django 4.2.23 on 2026-04-29 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_perfilusuario_fecha_nacimiento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialSalud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("glucemia", models.FloatField()),
                ("presion_sistolica", models.FloatField()),
                ("presion_diastolica", models.FloatField()),
                ("ritmo_cardiaco", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
