# Generated by Django 4.2.23 on 2026-04-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="nombre_completo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
