# Generated by Django 4.2.23 on 2025-09-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrocomida',
            old_name='alimentos',
            new_name='foods',
        ),
    ]
